# Generated by Django 5.2.4 on 2025-07-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuickieLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ql_name', models.CharField(max_length=64)),
                ('ql_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Quickie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=64)),
                ('youtube_id', models.CharField(max_length=64)),
                ('date_created', models.DateField()),
                ('q_body_split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickies.bodysplit')),
                ('q_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickies.quickielevel')),
                ('q_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickies.quickietype')),
            ],
        ),
        migrations.CreateModel(
            name='QuickieExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickies.exercise')),
                ('quickie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickie_exercises', to='quickies.quickie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
