# Generated by Django 5.2.4 on 2025-07-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickieLevel',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='ql_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='ql_value',
            new_name='l_value',
        ),
    ]
