# Generated by Django 5.2.4 on 2025-07-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickies', '0002_rename_quickielevel_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='e_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickies.level'),
            preserve_default=False,
        ),
    ]
