# Generated by Django 5.2.4 on 2025-07-25 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickies', '0003_exercise_e_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickie',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 13)),
        ),
        migrations.AlterField(
            model_name='quickie',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
