# Generated by Django 5.2.4 on 2025-07-28 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickies', '0004_alter_quickie_date_created_alter_quickie_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='e_body_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickies.bodysplit'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='e_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='e_youtube_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
