# Generated by Django 5.2.4 on 2025-07-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickies', '0005_exercise_e_body_split_exercise_e_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='e_description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
